export { compileSpell } from './compile.js'
export { compileMultiElement, getCombinedElement, ELEMENT_COMBINATION_RULES } from './multi-element.js'
export { compileMultiRing, compileLinkedRings } from './multi-ring.js'
export { buildSpellIR, buildInvalidSpell, generateSignature } from './spell-builder.js'
export { extractPrimarySigil } from './sigil-extractor.js'
export { aggregateSigns } from './sign-aggregator.js'
export { computeParameters } from './parameter-computer.js'
export { computeDirection } from './direction-computer.js'
export { computeQuality, computeStability, computeDuration } from './quality-scorer.js'
export { validateSpellInput } from './validate.js'
export { mergeWarnings, COMPILER_WARNING_MESSAGES } from './warnings.js'

export type { SpellBuilderInput } from './spell-builder.js'
export type { SigilExtractionResult } from './sigil-extractor.js'
export type { SignAggregationResult } from './sign-aggregator.js'
export type { ComputedParameters } from './parameter-computer.js'
export type { DirectionResult } from './direction-computer.js'
export type { QualityResult } from './quality-scorer.js'
export type { ValidationResult } from './validate.js'
export type { MultiElementInput } from './multi-element.js'

export const COMPILER_VERSION = '0.1.0'
